[package]
name = "bonk"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_vulkan = { version = "0.1.0", path = "../../lazy_vulkan" }
winit.workspace = true
yakui.workspace = true
yakui-vulkan.workspace = true
yakui-winit.workspace = true
