[package]
name = "prefab_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
hecs.workspace = true
serde.workspace = true
serde_json.workspace = true

engine_types.path = "../engine_types"
component_registry.path = "../component_registry"
