[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
engine_types.path = "../engine_types"

anyhow.workspace = true
git-version.workspace = true
log.workspace = true
hecs.workspace = true
