[package]
name = "bonk_gui"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
engine_types.path = "../engine_types"
yakui-shadcn.path = "../../yakui-shadcn/yakui-shadcn"

hecs.workspace = true
yakui-shadcn.workspace = true
yakui.workspace = true
