[package]
name = "component_registry"
version = "0.1.0"
edition = "2024"

[dependencies]
engine_types.path = "../engine_types"
hecs.workspace = true
serde.workspace = true
serde_json.workspace = true
